apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: jenkins-volume-claim
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi  
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
